final Map<String, String> eng_translations = {
  'search_games': 'Search Games',
  'discover_adventures': 'Discover New Adventures!',
  'explore_games':
      'Explore a vast collection of games and scenarios. Dive into unique storylines and find your next favorite game.',
  'find_games': 'Find Games',
  'recommended_games': 'Recommended Games',
  'home': 'Home',
  'game': 'Game',
  'search': 'Search',
  'profile': 'Profile',
  'available_gamebooks': 'Available Stories',
  'no_gamebooks_available': 'No Available Stories',
  'search_hint': 'Search users, scenarios...',
  'no_results_found': 'No results found',
  'user': 'User',
  'scenario': 'Scenario',
  'password': 'Password',
  'email': 'Email Address',
  'login_failed': 'Login Failed',
  'not_logged_in': 'Not Logged In',
  'login': 'Log In',
  'no_account_question': "Don't have an account?",
  'already_registered': 'Already have an account?',
  'register': 'Register',
  'name': 'Name',
  'confirm_password': 'Confirm Password',
  'settings': 'Settings',
  'language': 'Language',
  'notifications': 'Notifications',
  'theme': 'Theme',
  'light': 'Light',
  'dark': 'Dark',
  'system': 'System',
  'decision_layout_style': 'Decision Style',
  'reset_settings': 'Restore Defaults',
  'description': 'Description',
  'dates': 'Dates',
  'start_date': 'Start Time',
  'end_date': 'End Time',
  'steps': 'Step List',
  'no_steps': 'No steps available',
  'play_game': 'Play Game',
  'login_needed': 'You must log in',
  'edit_profile': 'Edit Profile',
  'logout': 'Log Out',
  'decision': 'Decision',
  'history': 'Story',
  'map': 'Map',
};
